# Generated by Django 6.0.5 on 2026-06-24 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=255, verbose_name='Vendor/Store Name')),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Groceries', 'Groceries'), ('Cleaning', 'Cleaning'), ('Staples', 'Staples'), ('Other', 'Other')], default='Groceries', max_length=50)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='UPI', max_length=50)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_expenses', to='property.property')),
            ],
            options={
                'verbose_name': 'Grocery Expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
