# Generated by Django 6.0.5 on 2026-06-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('sharing_type', models.CharField(choices=[('Single Sharing', 'Single Sharing'), ('Double Sharing', 'Double Sharing'), ('Triple Sharing', 'Triple Sharing'), ('Four Sharing', 'Four Sharing')], max_length=50)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField(default=0)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='property.property')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
