# Generated by Django 6.0.5 on 2026-06-24 14:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Kitchen', 'Kitchen Staff'), ('Takecare', 'Takecare / Caretaker'), ('Security', 'Security'), ('Manager', 'Property Manager'), ('Cleaning', 'Housekeeping')], default='Takecare', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=Decimal('12000.00'), help_text='Monthly base salary', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Current month payment status')),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
