# Generated by Django 6.0.5 on 2026-06-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('resident_name', models.CharField(max_length=200)),
                ('purpose', models.CharField(choices=[('Relative', 'Relative'), ('Delivery', 'Delivery'), ('Maintenance', 'Maintenance'), ('Guest', 'Guest')], default='Relative', max_length=50)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-OUT')], default='Checked-In', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='property.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors_room', to='rooms.room')),
            ],
        ),
    ]
