# Generated by Django 6.0.4 on 2026-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('PG', 'PG'), ('Co-living', 'Co-living'), ('Rented Building', 'Rented Building'), ('Room', 'Room'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Residence', 'Residence')], max_length=50),
        ),
    ]
